# Generated by Django 4.0.8 on 2022-12-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_sorting_criteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='guest_can_pause',
        ),
        migrations.RemoveField(
            model_name='room',
            name='votes_to_skip',
        ),
    ]
